--liquibase formatted sql
--changeset allan:05
--comment: create session and session time table
CREATE TABLE VTE.SESSION (
    ID_SESSION SERIAL PRIMARY KEY NOT NULL,
    ID_MOVIE INTEGER REFERENCES VTE.MOVIE(ID_MOVIE) NOT NULL,
    ID_MOVIE_THEATER INTEGER REFERENCES VTE.MOVIE_THEATER NOT NULL
);
--rollback DROP TABLE VTE.SESSION;

CREATE TABLE VTE.SESSION_TIME (
    ID_SESSION_TIME SERIAL PRIMARY KEY NOT NULL,
    ID_SESSION INTEGER REFERENCES VTE.SESSION(ID_SESSION),
    SESSION_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
    PRICE REAL NOT NULL,
    AVAILABLE_ASSENTS INTEGER NOT NULL
);
--rollback DROP TABLE VTE.SESSION_TIME;